apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9yb290MTk4OTpCb3NzTWFuQG15Zmlyc3RjbHVzdGVyLmRnb3llLm1vbmdvZGIubmV0L2NvdXJzZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  MONGO_DBNAME: Y291cnNl
