apiVersion: v1
kind: Secret
metadata: 
  name: mongo-sec
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9yb290MTk4OTpCb3NzTWFuQG15Zmlyc3RjbHVzdGVyLmRnb3llLm1vbmdvZG IubmV0L2NvdXJzZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  password: Qm9zc01hbg==   
  username: cm9vdDE5ODk=   
  