apiVersion: v1
kind: Secret
metadata:
  name: mongo-sec
type: Opaque
data:
  password: Qm9zc01hbg==
  username: cm9vdDE5ODk=
  MONGO_URI: bW9uZ29kYitzcnY6Ly9yb290MTk4OTpCb3NzTWFuQG15Zmlyc3RjbHVzdGVyLmRnb3llLm1vbmdvZGIubmV0L2NvdXJzZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
