apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30005  # Port on each node to expose the Service
      protocol: TCP
  type: NodePort
  selector:
    role: frontend