apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  ports:
    - port: 80
      targetPort: 5173  # Map the service's port 80 to the container's 5173
      protocol: TCP
  type: ClusterIP
  selector:
    role: frontend
