apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-ingress
  namespace: three-tier
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: api.example.com
    http:
      paths:
      # Route /user requests to the backend
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 5000
      # - path: /users
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: api
      #       port:
      #         number: 5000
      # Route root requests to the frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80  
