apiVersion: v1
kind: Secret
metadata: 
  namespace: three-tier
  name: mongo-cred
type: Opaque
data:
  MONGO_CONN_STR: bW9uZ29kYitzcnY6Ly9yb290MTk4OTpCb3NzTWFuQG15Zmlyc3RjbHVzdGVyLmRnb3llLm1vbmdvZGIubmV0L2NvdXJzZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  password: Qm9zc01hbg==  
  username: cm9vdDE5ODk=
